const FETCH_DASHBOARD_DATA = 'FETCH_DASHBOARD_DATA'
const FETCH_AGENT_DATA = 'FETCH_AGENT_DATA'
const FETCH_CALL_DATA = 'FETCH_CALL_DATA'

export { FETCH_DASHBOARD_DATA, FETCH_AGENT_DATA, FETCH_CALL_DATA }
