export const AGGREGATE_DATA_REQUEST = "AGGREGATE_DATA_REQUEST";
export const AGGREGATE_DATA_SUCCESS = "AGGREGATE_DATA_SUCCESS";
export const AGGREGATE_DATA_FAILURE = "AGGREGATE_DATA_FAILURE";

export const AGENT_DATA_REQUEST = "AGENT_DATA_REQUEST";
export const AGENT_DATA_SUCCESS = "AGENT_DATA_SUCCESS";
export const AGENT_DATA_FAILURE = "AGENT_DATA_FAILURE";

export const NUMBER_DATA_REQUEST = "NUMBER_DATA_REQUEST";
export const NUMBER_DATA_SUCCESS = "NUMBER_DATA_SUCCESS";
export const NUMBER_DATA_FAILURE = "NUMBER_DATA_FAILURE";